---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restapi-db-pvc
  namespace: dotnetrestapi
  labels:
    app: restapi-db
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
